name: Deploy Application

on:
  push:
    branches:
      - implement-render-deploy

jobs:
  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v4

  #     - name: Setup node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20.x
  #         cache: npm

  #     - name: Install
  #       run: cd team-finder-server && npm ci

  #     - name: Run tests
  #       run: cd team-finder-server && npm run test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait-for-success: true
