name: Deploy Application

on:
  push:
    branches:
      - implement-render-deploy

jobs:
  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v4

  #     - name: Setup node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20.x
  #         cache: npm

  #     - name: Install
  #       run: cd team-finder-server && npm ci

  #     - name: Run tests
  #       run: cd team-finder-server && npm run test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        run: npm run deploy
        env:
          MY_RENDER_SERVICE_ID: ${{ secrets.MY_RENDER_SERVICE_ID }}
          MY_RENDER_API_KEY: ${{ secrets.MY_RENDER_API_KEY }}
